# Fichier de configuration pour l'environnement de développement Docker
version: '3.8'

services:
  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: '!ChangeMe!'
    volumes:
      - db_data:/var/lib/postgresql/data:rw

  php:
    build:
      context: ./api_admin
      dockerfile: Dockerfile
    depends_on:
      - database
    volumes:
      - ./api_admin:/srv/app

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "8080:89"
    volumes:
      - ./api_admin/public:/srv/app/public:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

volumes:
  db_data:
